name: Test new changes in feature branch

on:
  push:
    branches: [ '*', '!master' ]

jobs:

  test_new_changes:
    name: Run tests and checks on a feature branch
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ job.status }}

    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check if .version file exists
      id: version_file_exists
      run: |
        if [[ -f .version ]]; then 
          echo "::set-output name=version_file_exists::true"
        else 
          echo "::set-output name=version_file_exists::false" 
        fi

    - name: Read out .version file
      if: steps.version_file_exists.outputs.version_file_exists == 'true'
      id: planned_version
      run: echo "::set-output name=planned_version::$(cat .version)"

    - name: Run shellcheck
      run: >-
        shellcheck fs_indexer.sh

    - name: Build
      run: make build

    - name: Run tests
      run: make test

    - name: Upload test results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: fs_indexer-${{ steps.planned_version.outputs.planned_version }}-test-results-${GITHUB_JOB}.tar.gz
        path: /tmp/fs_indexer-${{ steps.planned_version.outputs.planned_version }}-test-results.tar.gz
