name: Test new changes in feature branch

on:
  push:
    branches: [ '*', '!master' ]

jobs:

  test_new_changes:
    name: Run tests and checks on a feature branch
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ job.status }}

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install additional packages
        run: >-
          sudo apt-get install findutils

      - name: Check if .version file exists
        id: version_file_exists
        run: |
          if [[ -f .version ]]; then 
            echo "::set-output name=version_file_exists::true"
          else 
            echo "::set-output name=version_file_exists::false" 
          fi

      - name: Read out .version file
        if: steps.version_file_exists.outputs.version_file_exists == 'true'
        id: planned_version
        run: echo "::set-output name=planned_version::$(cat .version)"

      - name: Run shellcheck
        run: >-
          shellcheck fs_indexer.sh

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Define artifact name
        id: define_artifact_name
        shell: bash
        run: |
          echo "::set-output name=artifact_name::fs_indexer-${{ steps.planned_version.outputs.planned_version }}-test-results-${GITHUB_RUN_ID}.tar.gz"

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.define_artifact_name.outputs.artifact_name }}
          path: /tmp/fs_indexer-${{ steps.planned_version.outputs.planned_version }}-test-results.tar.gz
